#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "overleaf"
name = "Overleaf"
description.en = "Online real-time collaborative LaTeX editor"
description.fr = "Éditeur LaTeX collaboratif en ligne et en temps réel"

version = "2023.12.17~ynh1"

maintainers = []

[upstream]
license = "AGPL-3.0-or-later"
website = "https://www.overleaf.com"
userdoc = "https://www.overleaf.com/learn"
code = "https://github.com/overleaf/overleaf"

[integration]
yunohost = ">= 11.2.0"
architectures = "all"
multi_instance = false

ldap = true

sso = true

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr", "en"]
    default = "fr"

    [install.admin]
    type = "user"

[resources]
    [resources.sources]
        [resources.sources.main]
        url = "https://github.com/overleaf/overleaf/archive/ea4d63876aec15eea2b65923574d41a066b71477.tar.gz"
        sha256 = "9c9cbae9db51b9da7de06a4486fc8e676ead6336732ea5057c0008821003642a"
        autoupdate.stategy = "latest_github_commit"
        
      #  [resources.sources.ldap]
      #  url = "https://github.com/smhaller/ldap-overleaf-sl/archive/38887b9a152a7f35de1637789179ca1b60a63143.tar.gz"
      #  sha256 = "dc09531ee2dac273e3122a78dbcc3fedee4c90fcdac55a5dffe540247b5e5449"
      #  in_subdir = 2
      #  autoupdate.strategy = "latest_github_tag"


    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.data_dir]
    subdirs = [ "compiles", "output", "cache", "user_files", "template_files" ]

    [resources.permissions]
    main.url = "/"
    main.auth_header = false

    admin.url = "/launchpad"
    admin.allowed = "admins"
    admin.show_tile = false

    [resources.ports]
    main.default = 8095

    [resources.apt]
    packages = "texlive, texlive-xetex, texlive-base, texlive-font-utils, redis-server, latexmk, python3-pygments"
